chmod +rw linker.ld
chmod +rw linkerelf.ld
chmod +rw src/entry.asm
chmod +rw src/kit.asm
chmod +rw src/main.c
chmod +rw src/aux.c
chmod +rw src/aux.h
chmod +rw obj/entry.o
chmod +rw obj/main.o
chmod +xrw make.sh
